# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.11.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy to GCP
      uses: thesis/gcp-storage-bucket-action@v2.0.1
      with:
        service-key: ${{ secrets.TBTC_NETWORK_UPLOADER_SERVICE_KEY_JSON }}
        project: tbtc-prod
        bucket-name: tbtc.network
        build-folder: public
